env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

task:
    name: aosp # Project name
    timeout_in: 4h
    persistent_worker:
      labels:
        name: AX61-1
      isolation:
        container:
          image: apon77/aosp:cirrus
          cpu: 24
          memory: 60G
          volumes:
            - /home/cirrus/roms:/home/cirrus/roms
            - /home/cirrus/ccache:/home/cirrus/ccache
            - /home/cirrus/.config:/home/cirrus/.config
    sync_script: # To sync source
      - ./sync # Source sync script
    build_script: # Actual build script foreground
      - ./build # Build script to run